### ISSUE TITLE
How do I import using CocoaPods?

### ISSUE THREAD

**Issue by huanglins** [stackotter/swift-cmark-gfm#1]

**Comment by stackotter** [comment]
Sorry, this package doesn't support CocoaPods. However, I'd be happy to accept a PR that adds a `Podspec` to the package (I haven't used CocoaPods before). If you don't know how to create a `Podspec` file either I can look at the documentation and do it myself when I get the time (might not be soon).

**Comment by huanglins** [comment]
Thank you. I'll wait.

**Comment by stackotter** [comment]
I finally got around to trying to add a podspec. Unfortunately I've never used cocoapods in my life and I didn't manage to get it working. Here's the podspec I created (I couldn't verify it because when I run `pod lib lint` I just get some weird Xcode simulator related errors. Feel free to add checkout this repo and create a `SwiftCMarkGFM.podspec` file with the contents I've put below, and see if `pod lib lint` works. If the podspec works for you I can add it to the repo.

```rb
Pod::Spec.new do |s|
  s.name             = 'SwiftCMarkGFM'
  s.version          = '1.0.2'
  s.summary          = 'The C API of CMark GFM as a Swift package (with no wrapping API).'
  s.homepage         = 'https://github.com/stackotter/swift-cmark-gfm'
  s.license          = { :type => 'Apache 2.0', :file => 'LICENSE' }
  s.author           = { 'stackotter' => 'stackotter@stackotter.dev' }
  s.source           = { :git => 'https://github.com/stackotter/swift-cmark-gfm', :tag => s.version.to_s }
  s.swift_version = '5.1'
  s.source_files = 'Sources/CmarkGFM/**/*'
end
```

I'll close this issue for now as CocoaPods support isn't really on my agenda for this project (most new packages don't support CocoaPods anymore because Swift Package Manager is much better integrated with Swift, but I do understand that some people work for companies using CocoaPods and don't have a choice)
